version: '3.4'

services:
  codegolf.web:
    image: ${DOCKER_REGISTRY-}codegolfweb
    build:
      context: .
      dockerfile: CodeGolf.Web/Dockerfile

  codegolf.executionserver:
    image: ${DOCKER_REGISTRY-}codegolfexecutionserver
    build:
      context: .
      dockerfile: CodeGolf.ExecutionServer/Dockerfile

