version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build/
    steps:
      - checkout
      - run:
          name: Run result
          command: |
            pushd ./Tests/CodeGolf.Unit.Test/
            dotnet clean
            dotnet test
            popd

  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn --cwd ./CodeGolf.Web/ClientApp/codeGolf/ install --prod
      - run:
          name: Run Tests
          command: yarn --cwd ./CodeGolf.Web/ClientApp/codeGolf/ test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
