version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build/
    steps:
      - checkout
      - run:
          name: Run result
          command: |
            pushd ./Tests/CodeGolf.Unit.Test/
            dotnet clean
            dotnet test
            popd

  test:
    working_directory: ~/CodeGolf/CodeGolf.Web/ClientApp/codeGolf/
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
