version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    working_directory: /build/
    steps:
      - checkout
      - run:
          name: Run result
          command: |
            pushd ./Tests/CodeGolf.Unit.Test/
            dotnet clean
            dotnet test
            popd
